services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  app:
    build: ./app
    depends_on:
      - opensearch
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net: